create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  email text not null check (char_length(email) <= 160),
  message text not null check (char_length(message) between 3 and 2000),
  created_at timestamptz not null default now()
);

alter table public.contacts enable row level security;

create index if not exists idx_contacts_created_at_desc
on public.contacts (created_at desc);
